[package]
name = "prover_key_gen"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
manta-api = { branch = "manta", git = "https://github.com/Manta-Network/manta-api", features = ["std"] }
